Repository maityamit/Tracky-Track-your-goals-or-targets, pull requests merged in 2022-03, with the labels that each got.

#128 Show log dialog box
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
  app/src/main/res/layout/show_log_dialog.xml
Labels: JWOC, medium

#129 Added Graph Preview
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GraphConsistency.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active/GoalAdapter.java
  app/src/main/res/layout/activity_graph_consistency.xml
  app/src/main/res/layout/activity_profile.xml
Labels: JWOC, hard

#131 Rank list functionality added
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/RegisterActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/Topper.java
  app/src/main/res/layout/fragment_rank.xml
  app/src/main/res/layout/rank_list_item.xml
Labels: JWOC, hard

#136 Added Dialog Input Text
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/res/values/style.xml
Labels: JWOC, medium, PR: unreviewed, PR: reviewed-approved

#138 Delete archive goal automatically after a particular time
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveGoalFragment.java
  app/src/main/res/layout/archive_goals_item_layout.xml
Labels: JWOC, hard, PR: unreviewed

#139 Showing "Me" instead of username on rank list
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankFragment.java
Labels: JWOC, medium, PR: unreviewed

#142 Profile Image update issue fixed
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
Labels: JWOC, easy, PR: unreviewed

#148 Streak Notes Done
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/Notes.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/notelist.xml
Labels: JWOC, medium, PR: unreviewed

#150 Added BG for Consistency
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/drawable/blueish_bg.xml
  app/src/main/res/drawable/greenish_bg.xml
  app/src/main/res/drawable/orangish_bg.xml
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium, PR: reviewed-approved

#151 Fixed Number Input issue
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, easy, PR: unreviewed, PR: reviewed-approved

#154 Fixed Take Break Bug
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, easy, PR: reviewed-approved

#159 Added Cancel Break Feature
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium, PR: reviewed-approved

#160 Reset Feature Added
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/drawable/reset.xml
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium, PR: reviewed-approved

#162 Material Dialog Box for Logout
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
Labels: JWOC, easy, PR: reviewed-approved

#163 Login with OTP Done
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/PhoneNoSignin.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/VerifyOTP.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/RegisterActivity.java
  app/src/main/res/drawable/phone.xml
  app/src/main/res/layout/activity_phone_no_signin.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_verify_otp.xml
Labels: JWOC, hard, PR: unreviewed

#164 Added New UI
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/RegisterActivity.java
  app/src/main/res/drawable/backgroud_grad.xml
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/drawable/clock.png
  app/src/main/res/drawable/editfield.xml
  app/src/main/res/drawable/esign.xml
  app/src/main/res/drawable/fpass.png
  app/src/main/res/drawable/gitgub.xml
  app/src/main/res/drawable/github_image.png
  app/src/main/res/drawable/gradient_last_step_bg.xml
  app/src/main/res/drawable/gradient_visulization_bg.xml
  app/src/main/res/drawable/gradient_welcome_bg.xml
  app/src/main/res/drawable/gsign.xml
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/ic_baseline_logout_24.xml
  app/src/main/res/drawable/illus.png
  app/src/main/res/drawable/reminder_button_background.xml
  app/src/main/res/drawable/reminder_page_background.png
  app/src/main/res/drawable/set_reminder_background.xml
  app/src/main/res/drawable/signin_ill.png
  app/src/main/res/drawable/top1.png
  app/src/main/res/drawable/top1c.png
  app/src/main/res/drawable/top2.png
  app/src/main/res/drawable/welcome.png
  app/src/main/res/drawable/white_button.xml
  app/src/main/res/layout/activity_addgoal.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_forgetpass.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_archive_goal.xml
  app/src/main/res/layout/fragment_rank.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/rank_list_item.xml
Labels: JWOC, hard, PR: reviewed-approved

#168 UI changed in Add Goal Activity
  .idea/misc.xml
  app/src/main/res/layout/activity_addgoal.xml
Labels: JWOC, easy, PR: unreviewed

#166 Added Share Link of Playstore
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
Labels: JWOC, easy, PR: unreviewed

#167 Share Button Issue solved
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveGoalFragment.java
  app/src/main/res/layout/fragment_archive_goal.xml
Labels: JWOC, medium, PR: unreviewed

#179 Dev testing
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/PhoneNoSignin.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/VerifyOTP.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/RegisterActivity.java
  app/src/main/res/drawable/phone.xml
  app/src/main/res/layout/activity_phone_no_signin.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_verify_otp.xml
Labels: PR: unreviewed

#185 Added Button to remove all goal at once
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
  app/src/main/res/layout/fragment_settings.xml
Labels: JWOC, medium, PR: unreviewed

#190 UI changed in Some Activities
  app/src/main/res/layout/activity_addgoal.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: JWOC, medium, PR: unreviewed

#192 Added Restrictions that removes edit, take break and alarm button when goal is completed
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium, PR: reviewed-approved

#193 Added Logo
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/logo.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_phone_no_signin.xml
  app/src/main/res/layout/activity_verify_otp.xml
Labels: JWOC, easy, PR: reviewed-approved

#194 Added new Illustrations and Icons
  .idea/misc.xml
  app/src/main/res/drawable/bronzet.png
  app/src/main/res/drawable/goldt.png
  app/src/main/res/drawable/n1.xml
  app/src/main/res/drawable/no1.png
  app/src/main/res/drawable/no2.png
  app/src/main/res/drawable/silvert.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_active_goal.xml
  app/src/main/res/layout/fragment_archive_goal.xml
  app/src/main/res/layout/fragment_rank.xml
Labels: JWOC, medium

#196 Added Email Cross Check
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, hard, PR: unreviewed, PR: reviewed-approved

#198 Fixed Reset Goal Bug
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, medium, PR: unreviewed

#201 Rate Feature Done in Settings Fragment
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
Labels: JWOC, medium, PR: unreviewed

#202 Fixed Undone Task
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/reset_dialog.xml
Labels: PR: unreviewed

#206 Dialog Box Added In Settings Fragment
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
Labels: JWOC, easy, PR: unreviewed

#209 Added Screenshots and Banner for Playstore
  Images Demo/ss/1.png
  Images Demo/ss/2.png
  Images Demo/ss/3.png
  Images Demo/ss/4.png
  Images Demo/ss/5.png
  Images Demo/ss/6.png
  Images Demo/ss/7.png
  Images Demo/ss/Banner.png
Labels: JWOC, hard, PR: reviewed-approved

#210 Progress dialog box fix
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, easy, PR: unreviewed

#213 Improved Card Design
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/GoalAdapter.java
  app/src/main/res/layout/archive_goals_item_layout.xml
  app/src/main/res/layout/main_tiles_layout.xml
Labels: JWOC, medium, PR: unreviewed

#211 Image matches background color
  app/src/main/res/drawable/empty_archive_image.png
  app/src/main/res/drawable/empty_goal_image.png
Labels: JWOC, easy, PR: unreviewed, PR: reviewed-approved

#219 Update name
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
Labels: JWOC, easy, PR: unreviewed

#222 Fixed Dashboard and Add Goal Activity issue
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/res/drawable/edit2.xml
  app/src/main/res/layout/activity_addgoal.xml
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium, PR: reviewed-approved

#224 Added Animation after Sign In Process
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignInDone.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/VerifyOTP.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/RegisterActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/SigninActivity.java
  app/src/main/res/layout/activity_sign_in_done.xml
  app/src/main/res/raw/tick.json
Labels: JWOC, medium, PR: unreviewed

#226 Fixed LeaderBoard Design
  .idea/misc.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_rank.xml
  app/src/main/res/layout/rank_list_item.xml
Labels: JWOC, medium, PR: unreviewed

#227 Privacy Policy Added
  Images Demo/PrivacyPolicy
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
Labels: JWOC, easy, medium, PR: reviewed-approved

#234 Progress Dialog Box Fixed
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, easy, PR: unreviewed, PR: reviewed-approved

#237 Graph Color Change Done
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/res/values/colors.xml
Labels: JWOC, medium, PR: reviewed-approved

#240 Added Animation in LeaderBoard
  .idea/misc.xml
  app/src/main/res/layout/fragment_rank.xml
  app/src/main/res/raw/confetti1.json
Labels: JWOC, easy, PR: reviewed-approved

#241 Added Ripple Effect
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/drawable/ripple_blue.xml
  app/src/main/res/drawable/ripple_red.xml
  app/src/main/res/layout/activity_addgoal.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_forgetpass.xml
  app/src/main/res/layout/activity_phone_no_signin.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_verify_otp.xml
  app/src/main/res/layout/dialog_fragment.xml
  app/src/main/res/layout/fragment_active_goal.xml
  app/src/main/res/layout/fragment_archive_goal.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/reset_dialog.xml
Labels: JWOC, easy, PR: unreviewed

#244 Issue #232 Done
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
  app/src/main/res/drawable/banner.png
  app/src/main/res/layout/fragment_settings.xml
Labels: JWOC, medium, PR: unreviewed

#246 Add Graph in Dashboard
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, hard, PR: unreviewed, PR: reviewed-approved

#249 Reset button confirmation dialogue box
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, easy, PR: unreviewed

#250 Added Goal Counter
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java
  app/src/main/res/layout/fragment_active_goal.xml
Labels: JWOC, easy, PR: reviewed-approved

#252 Goal Description Retrieved
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
Labels: JWOC, medium, PR: unreviewed

#259 Logo changed in Splash Screen
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/layout/activity_splassh.xml
Labels: JWOC, easy, PR: unreviewed

#260 Added Feedback and Card Changes
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/GoalAdapter.java
  app/src/main/res/drawable/feedbk.xml
  app/src/main/res/drawable/gr.xml
  app/src/main/res/drawable/rd.xml
  app/src/main/res/drawable/yl.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/main_tiles_layout.xml
Labels: JWOC, medium, PR: unreviewed

#261 Fixed Splash Screen
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/splash/SplasshActivity.java
Labels: JWOC, easy, PR: unreviewed

#262 Fixed Issue No 257
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
Labels: JWOC, easy, PR: unreviewed

#263 Auto delete archive goal
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/GoalAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveClass.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveGoalFragment.java
Labels: enhancement, JWOC, hard, PR: reviewed-approved

#264 Added Card Dialog to show User details in Leaderboard
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankFragment.java
  app/src/main/res/layout/user_display.xml
  app/src/main/res/values/strings.xml
Labels: JWOC, hard, PR: unreviewed

#265 Search bar UI changed
  .idea/misc.xml
  app/src/main/res/font/alice.xml
  app/src/main/res/font/balthazar.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_active_goal.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: JWOC, medium, PR: unreviewed

#268 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: unreviewed

#270 Search bug fixed
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java
Labels: JWOC, easy, PR: reviewed-approved
