Repository maityamit/Tracky-Track-your-goals-or-targets, pull requests merged in 2022-02, with the labels that each got.

#15 Adding alert dialog for confirmation of logout
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
Labels: JWOC, easy

#16 Creating AlertDialog Box
  .idea/discord.xml
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
Labels: JWOC, hard

#17 Added Progress Dialog
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
  app/src/main/res/drawable/bg_round.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/progress_diaglog.xml
Labels: JWOC, easy

#18 consistency display updated
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
Labels: JWOC, easy

#22 Signup and Signin feature added
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ForgetpassActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/RegisterActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SigninActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/Users.java
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/stroke.xml
  app/src/main/res/layout/activity_forgetpass.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
Labels: JWOC, medium

#32 Added 3 UI designs
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java
  app/src/main/res/drawable/button.xml
  app/src/main/res/drawable/edittextbox.xml
  app/src/main/res/drawable/illus.png
  app/src/main/res/drawable/plus.png
  app/src/main/res/drawable/profile.png
  app/src/main/res/drawable/top1.png
  app/src/main/res/drawable/top1c.png
  app/src/main/res/drawable/top2.png
  app/src/main/res/drawable/top2c.png
  app/src/main/res/layout/activity_forgetpass.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: JWOC, medium

#33 Profile Activity UI Design Done
  .idea/misc.xml
  app/src/main/res/drawable/communicate.png
  app/src/main/res/drawable/logout_btn.xml
  app/src/main/res/drawable/logout_button.xml
  app/src/main/res/drawable/man.png
  app/src/main/res/layout/activity_profile.xml
Labels: JWOC, easy

#35 Added option to upload profile picture
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
Labels: JWOC, hard

#37 a new xml added for addTripActivity
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddtripActivity.java
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/ic_wave__9.xml
  app/src/main/res/layout/activity_addtrip.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: JWOC, easy

#44 When goal ( end date = current date +1 ) the goal will automatically go to archive section.
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ArchiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/MyAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveClass.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveGoalFragment.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/archive_goals_item_layout.xml
  app/src/main/res/layout/fragment_active_goal.xml
  app/src/main/res/layout/fragment_archive_goal.xml
  app/src/main/res/values/strings.xml
Labels: bug, JWOC, hard

#47 5 minor issues done
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java
  app/src/main/res/drawable/material_dialog_box.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/values/style.xml
Labels: JWOC, medium

#50 Image Upload option implemented on Signup Activity
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java
  app/src/main/res/layout/activity_signup.xml
Labels: JWOC, easy

#53 Search function for searching goals added
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/RegisterActivity.java
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_active_goal.xml
Labels: JWOC, hard

#56 Displaying message when no item present in active and archive lists
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveGoalFragment.java
  app/src/main/res/drawable/empty_archive_image.png
  app/src/main/res/drawable/empty_goal_image.png
  app/src/main/res/layout/fragment_active_goal.xml
  app/src/main/res/layout/fragment_archive_goal.xml
Labels: JWOC, easy

#60 Added Username Update Feature
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/res/layout/activity_profile.xml
Labels: bug, JWOC, easy

#68 DashboardActivity Changes
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/values/colors.xml
Labels: JWOC, medium

#70 Delete goal option added
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, easy

#72 Highlights multiple date using MCalendarView
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/drawable-v24/calendar_background.xml
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, hard

#75 Changed Action Button Style + UX
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/res/drawable/add.xml
  app/src/main/res/layout/activity_home.xml
Labels: JWOC, easy

#76 Redesigned alarm activity
  .idea/misc.xml
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/drawable/reminder_button_background.xml
  app/src/main/res/drawable/reminder_page_background.png
  app/src/main/res/drawable/set_reminder_background.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/values/strings.xml
Labels: JWOC, easy

#80 Something
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
Labels: JWOC, medium

#81 Added PDF Feature
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
  app/src/main/res/layout/activity_profile.xml
Labels: JWOC, hard

#82 Added Duplicate Name restriction Feature
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
Labels: JWOC, medium

#84 App intro added in this Application.
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/activity/AppIntroActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/LastStepFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/VisulizationFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/WelcomeFragment.java
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/drawable-v24/create_and_go.png
  app/src/main/res/drawable-v24/dashboard.png
  app/src/main/res/drawable/create_and_go.png
  app/src/main/res/drawable/dashboard.png
  app/src/main/res/drawable/gradient_last_step_bg.xml
  app/src/main/res/drawable/gradient_visulization_bg.xml
  app/src/main/res/drawable/gradient_welcome_bg.xml
  app/src/main/res/drawable/slider_button_shape.xml
  app/src/main/res/layout/activity_app_intro.xml
  app/src/main/res/layout/fragment_last_step.xml
  app/src/main/res/layout/fragment_visulization.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/intro_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: JWOC, hard

#91 Removed Floating Action Button from other fragments
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_active_goal.xml
Labels: JWOC, easy

#96 Goal pic upload feature added
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium

#98 Store and retrieve user activity from firebase
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
Labels: JWOC, hard

#102 Add Share Features
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium

#103 Retrieve Goal Image into CurrentGoal Frag Recyclerview items Done
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java
  app/src/main/res/layout/main_tiles_layout.xml
Labels: JWOC, medium

#105 Added On Break Feature
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, hard

#104 Consistency Percentage Progress Bar on Archived Goals
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveAdapter.java
  app/src/main/res/layout/archive_goals_item_layout.xml
Labels: JWOC, medium

#109 Issue #93 fixed - Uploading Max Consistency
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/Topper.java
Labels: JWOC, hard

#110 Fixed Edit issue
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Labels: JWOC, medium

#111 Layout for Rank Fragment and Recycler View Item
  .idea/misc.xml
  .idea/render.experimental.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/RankAdapter.java
  app/src/main/res/drawable/leaderboard_first.png
  app/src/main/res/drawable/leaderboard_second.png
  app/src/main/res/drawable/leaderboard_third.png
  app/src/main/res/layout/fragment_rank.xml
  app/src/main/res/layout/rank_list_item.xml
Labels: JWOC, easy

#114 NewNoteCreation
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java
  app/src/main/res/drawable/addnew.xml
  app/src/main/res/layout/activity_dashboard.xml
Labels: JWOC, medium

#119 Added Onboarding Screen with New UI
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/IntroViewPagerAdapter.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/Onboarding.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/ScreenItem.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SplasshActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/activity/AppIntroActivity.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/LastStepFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/VisulizationFragment.java
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/appIntro/slider/WelcomeFragment.java
  app/src/main/res/anim/button_animation.xml
  app/src/main/res/drawable/black_fill.xml
  app/src/main/res/drawable/indicator_default.xml
  app/src/main/res/drawable/indicator_selected.xml
  app/src/main/res/drawable/indicator_selector.xml
  app/src/main/res/drawable/next_btn.xml
  app/src/main/res/drawable/s1.png
  app/src/main/res/drawable/s2.png
  app/src/main/res/drawable/s3.png
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_splassh.xml
  app/src/main/res/layout/layout_screen.xml
Labels: JWOC, hard

#123 Added Automatic Reminder to remind user to complete goals
  .idea/gradle.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java
Labels: JWOC, medium

#125 Splash Screen Done
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/achivementtrackerbyamit/example/achivetracker/SplasshActivity.java
  app/src/main/res/font/lato.xml
  app/src/main/res/font/lato_thin.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_splassh.xml
  app/src/main/res/raw/animatedlogo.json
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: JWOC, medium
